import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import HeroSection from "@/components/HeroSection";
import ProductsSection from "@/components/ProductsSection";

const notoSans = Noto_Sans({
  variable: "--font-noto-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable} font-sans antialiased`}>
        <div className={`relative`}>
          <div
            className={`relative mx-auto w-full xl:max-w-[1280px] md:max-w-[768px] max-w-[375px] mt-4 px-4 md:px-8`}
          >
            <Header />
            {children}
          </div>
          <div
            className={`absolute top-0 bg-white w-full mt-[70px] mx-4 left-1/2 -translate-x-1/2 h-full z-[-1]`}
          ></div>
        </div>
      </body>
    </html>
  );
}
